### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np


In [14]:
# Задаем диагональную матрицу и функцией реверсия разворачиваем ее
N = 10
print(list(reversed(np.arange(0, N))))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [30]:
# Создаем диагональную матрицу и суммируем по  диагонали
N = 5
a= list(reversed(np.arange(0, N)))
print('Сумма по диагонали: ',np.sum(a))
print(np.diag(a))


Сумма по диагонали:  10
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [31]:
N = 5
a= list(reversed(np.arange(0, N)))
print('Сумма по диагонали: ',np.diag(a).sum())
print(np.diag(a))

Сумма по диагонали:  10
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [ ]:
в = np.arange(0, N)

### Задание 3
Решите систему уравнений:   
4x + 2y + z = 4   
x + 3y = 12   
5y + 4z = -3

In [33]:
### Записываем значения x, y, z  в виде матрицы
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]] )
### Записываем  значения правой части уравнений
b = np.array([4, 12, -3])

In [36]:
### Импортируем модуль numpy.linalg для решения линейных уравнений
from numpy import linalg

In [37]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [41]:
### Делаем проверку решения
np.allclose(np.dot(a, linalg.solve(a, b)), b)

True